services:
  app:
    build:
      context: .
      args:
        WWWUSER: 1000
        WWWGROUP: 1000
    container_name: medical-app
    ports:
      - '8085:8080'
      - '5173:5173'
    volumes:
      - .:/var/www:cached
      - /var/www/node_modules
      - /var/www/vendor
    depends_on:
      - redis
    networks:
      - medical-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: medical-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - medical-network
    command: redis-server --appendonly yes
    restart: unless-stopped

networks:
  medical-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
